apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hamster  
  template:
    metadata:
      labels:
        app: hamster
    spec:
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 65534
      containers:
        - name: hamster
          image: registry.k8s.io/ubuntu-slim:0.1          
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          command: ["/bin/sh"]
          # args: ["-c", "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"]
          # Alpine uses BusyBox timeout which requires -t flag (not GNU timeout syntax)
          args: ["-c", "while true; do timeout 0.5s yes >/dev/null; sleep 0.5; done"]
          # args:
          #   - "-c"
          #   - "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"