# This is a SecretProviderClass example using user-assigned identity to access your key vault
# Service Connector sets up the Azure resource connection, users only need create the SecretProviderClass and workload resources
# For the variables to fill in, you may get their values from Service Connector Azure Portal


apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-demo-keyvault-csi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                        # Set to true for using managed identity
    userAssignedIdentityID: 4c11293a-47ae-45e5-ae88-461cab43a88f  # Set the clientID of the user-assigned managed identity to use
    keyvaultName: mykv2026                 # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: ExampleSecret            # keyvault secret name
          objectType: secret
    tenantId: a0f6b436-9821-405b-9724-8ffbbbe05049                 # az keyvault show --name KVNAME --query "properties.tenantId" -o tsv